### ISSUE TITLE
len is weird

### ISSUE THREAD

**Issue by Timmmm** [chaimleib/intervaltree#137]
```
>>> from intervaltree import Interval, IntervalTree
>>> len(Interval(2, 4))
3
```

Not what you expect! I guess this is because `Interval` is a 3-tuple or something? Maybe worth overriding `__length__` or whatever?

**Comment by chaimleib** [comment]
The `__len__` method is expected to return an integer, equal to the number of items in the receiver. In other words, a whole number. Since intervals are allowed to be any orderable type, including reals and timestamps and so on, it does not make sense to override `__len__` with the difference between the `begin` and `end` fields.

The Python documentation shows that `__len__`, which is invoked via `len(s)`, should count the number of items:
> `len(s)`
> Return the length (the number of items) of an object. The argument may be a sequence (such as a string, bytes, tuple, list, or range) or a collection (such as a dictionary, set, or frozen set).
> ~ https://docs.python.org/3/library/functions.html#len

> `object.__len__(self)`
Called to implement the built-in function [len()](https://docs.python.org/3/library/functions.html#len). Should return the length of the object, an integer >= 0.
> ~ https://docs.python.org/3/reference/datamodel.html#object.__len__

**Comment by Timmmm** [comment]
Maybe it would make more sense to not implement `len` at all then (or raise an exception if you call it).

The argument is not a collection or a sequence, as required by the docs.

**Comment by chaimleib** [comment]
Intervals are implemented as namedtuples. They are collections, and so they should behave in the standard way for namedtuples.

**Comment by Timmmm** [comment]
That feels like an implementation detail and a bit of an API foot-gun... Your library though!
