### ISSUE TITLE
Save and reload interval tree quickly

### ISSUE THREAD

**Issue by rob-myers** [chaimleib/intervaltree#47]
Hi,
Is it possible to save an interval tree, so that it can be loaded quickly later?
One could certainly save the set of intervals, but I want to avoid the rebuild time.
Cheers.

**Comment by chaimleib** [comment]
Build time is O(n log n) because the memory usage of the tree is O(n log n). Even if we stored all of that data on disk and reloaded it directly, build time would still be O(n log n).

It may be possible to achieve some constant scale factor of improvement by storing all that memory, but then the on-disk storage size would be several times bigger, proportional to log n.

**Comment by rob-myers** [comment]
Proportional yes, but constants and scale factors can make a difference.
I'll look at the source -- and thanks for the great library!
