### ISSUE TITLE
a different intersection operation

### ISSUE THREAD

**Issue by zfrenchee** [chaimleib/intervaltree#51]
I have a big `IntervalTree` and a small `IntervalTree`. For convenience, let's call them `A` and `B`. 

I want to do a big overlap query, such that I get, for every member of B, a list of A intervals that overlap with it. `tree.search` does this for a single point or interval, so I *can* iterate one tree, I suppose, but I suspect this function exists in the library, I just can't seem to find it. 

The documentation lists `result_tree = tree1 & tree2` but I don't want a result tree, I want a list of all the intervals from `tree2` which intersect with each of the intervals in `tree1`. Presumably the other functions listed under the intersection bullet do the same thing. 

---

On another note, the documentation says: 
```
- Membership queries

interval_obj in tree (this is fastest, O(1))
tree.containsi(begin, end, data)
tree.overlaps(point)
tree.overlaps(begin, end)
```

Why is `tree.overlaps` a membership query? That seems unintuitive, when a couple bullets above, you have `Overlap queries`.

**Comment by zfrenchee** [comment]
Hi @chaimleib, thanks for getting back to me. Three questions:
1. Why are you calling `sorted`? 
2. To make this query optimal, should `tree1` or `tree2` be the larger tree, in your example, or does it not matter? 
3. I'm not sure the way you've written it is the query I want. I'm looking for an output of roughly:
```
[ interval_from_tree1: [interval_from_tree2, other_interval_from_tree2], other_interval_from_tree1: [] ]
```

**Comment by chaimleib** [comment]
1. I like using `sorted()`, because it simplifies debugging for me. As noted, you could also use `list()` if ordering isn't important.

2. In my example, it should be faster with `tree2` being the smaller tree. Using n1 and n2 as the sizes of `tree1` and `tree2` respectively: we are running n2 calls (o(n2)) to `tree1.overlaps()` (o(log n1)). So, the order of growth is O(n2 * log n1) (as long as the ranges of `tree2`'s intervals are much smaller than the full extent of `tree1`).

3. It looks like you want a dict comprehension, not a list comprehension. Assuming you aren't using Python 2.6 or earlier, you could try this:

```python
result_tree = {iv: tree1.search(iv) for iv in tree2}
```
The `search()` method will take either ranges or `Interval`s.

**Comment by chaimleib** [comment]
Regarding your question of adding this operation to the library, my approach in designing the API was to make a general-purpose data structure. I realized that there were hundreds of useful methods I could add that would help in certain special situations. However, most of them would be one-liners like the above, and most would not be very adaptable. In addition, this would clutter the documentation with many confusingly similar methods, which is already a problem, as you noticed.

Rather than implement them all, I have only been including methods that could be used as a basis to make writing these one-liners easy.

That said, I do make exceptions for methods that require access to the internals of the tree, or are sufficiently complicated to write and are general enough in purpose that it would help lots of different programs.

I'd love to hear about further improvements you'd like me to implement! It makes me really happy that my library is useful, and I'd love to make it even more helpful! Whenever I get a message like this from people like you, it really makes my day!

**Comment by zfrenchee** [comment]
Hi @chaimleib 
I'm delighted to make your day. Your library is indeed terrifically useful, and has a beautifully simple interface. I agree with your philosophy of not adding too many methods, but I'm a little surprised mine didn't make the cut, given how elementary I think it is. I feel like it would be the natural return type of `tree1.search(tree2)` which I suppose is undefined in this library (?)

One note: the README doesn't seem to list searching by interval as an option (`tree.search(iv)`). Might be worth adding. 

Thanks again for all the help!
