### ISSUE TITLE
support for null intervals

### ISSUE THREAD

**Issue by mtivadar** [chaimleib/intervaltree#59]
it should be nice to support null intervals, like [4, 4]

**Comment by chaimleib** [comment]
There have been many requests to include points within the range search. I tried doing this once, but the algorithms for traversing and modifying the tree really depend on intervals containing some range. So, if you would like to include 4 in your interval tree, you could add the interval `[4, 5)`, which would start at 4 inclusively and end at 5 without including it, which is how all intervals work in the IntervalTree. They include the start value, but not the end value.

This behavior is analogous to string or array indexing:

```python
>>> s = "abcde"
>>> s[4:5]
"d"
>>> s[4:4]
""

>>> a = range(5)
>>> a[4:5]
[4]
>>> a[4:4]
[]
```

If your ranges are not discrete values, for example, they are reals with fractional parts, then for now, I would suggest coding around [`sortedcontainers.sorteddict`](http://www.grantjenks.com/docs/sortedcontainers/sorteddict.html). This is how I would like to add point support in a future release, but to a new class with a different name, since this is different in behavior from the current interval tree.

**Comment by kotoroshinoto** [comment]
in the case where left is included and right is excluded a position described as i:i would refer to the location between i-1 and i, not including either i-1 or i themselves.

to give context for this, a description of an insertion mutation in a genome would refer to a position between nucleotides as the location of origin for the variant, because that "range" doesn't exist in the reference sequence, but rather has a 'location' that lies between existing positions

**Comment by chaimleib** [comment]
In order to support using floats and other non-integer ranges, `Interval`s include the lower bound, but not the upper bound, so `Interval(2:3)` is `2 ≤ x < 3`. This is a deep dependency in the search, insertion and balancing algorithms, and other methods of `IntervalTree`.

If you tried to create `Interval(3, 3)`, you would get `3 ≤ x < 3`. There is no `x` that satisfies this inequality, since `x = 3` won't satisfy `x < 3`.

**Comment by gbuckholtz** [comment]
It is useful for me to have null intervals in the context I am using the intervaltree.   I am making an interval tree of CIDR format IP addresses.  1.0.254.0/23 for example.  There is a degenerate case of 1.0.254.0/32  that boils down to a single IP address rather than a range.

**Comment by GillesJ** [comment]
Handling of null intervals is a better fit conceptually where the intervals represent unit positions in data sets.
My use-case is in natural language processing where sequences of words in text are labelled. Often you want to assess if annotations in running text overlap. Any text dataset has a lot of one-word length annotations. [Word spans] are typically represented by intervals of word positions, e.g. [0,1] = [Word spans]. As mentioned, you can transform the positional representation to boundary representation by "end_position + 1" in combination with exclusive right boundary matching.
However the programmer has to always be cognizant of this representative transformation.

I used to use Sympy for text problems because it is a better fit conceptually as it casts null intervals to FiniteSet objects. But Sympy is way too slow and memory intensive on large datasets. Intervaltree.py is fast and light, so I will keep using this package over Sympy.
