### ISSUE TITLE
Return index of the interval

### ISSUE THREAD

**Issue by andreydung** [chaimleib/intervaltree#60]
Could tree.search(Interval) returns the index of the intervals? Assuming that originally, intervals are indexed from 0 to N when inserted into the tree.

**Comment by chaimleib** [comment]
Because intervals are allowed to overlap, there are multiple ways to order the intervals, some more appropriate in certain contexts than others. I decided not to impose my idea of sorting on you, so `IntervalTree` does not sort its output values unless you sort them yourself.

If each interval must have a unique identifier or index, I would include it in the `data` field of your `Interval`s, which you can structure however you like.

**Comment by andreydung** [comment]
Yes, including the index into the data field is a good idea!
